const dataBase = [{
    id: "1",
    nombre: "Nike Air Max 1",
    precio: 7000,
    talle: 40,
    stock: 20,
    imagen: '/assets/air-max-1.jpg',
    categoria: "mujer",
  },{
    id: "2",
    nombre: "Nike Air Max 720",
    precio: 9000,
    talle: 41,
    stock: 20,
    imagen: '/assets/air-max-720.jpg',
    categoria: "hombre",
  },{
    id: "3",
    nombre: "Nike Air Max 270",
    precio: 10000,
    talle: 40,
    stock: 20,
    imagen: '/assets/air-max-270.jpg',
    categoria: "niños",
  },{
    id: "4",
    nombre: "Nike SB Max",
    precio: 10000,
    talle: 40,
    stock: 20,
    imagen: '/assets/sb-max-premium.jpg',
    categoria: "hombre",
  },{
    id: "5",
    nombre: "Nike SB Air Max 2",
    precio: 11000,
    talle: 40,
    stock: 20,
    imagen: '/assets/sb-air-max-2.jpg',
    categoria: "sale",
  },{
    id: "6",
    nombre: "Nike Star Runner",
    precio: 11000,
    talle: 40,
    stock: 20,
    imagen: '/assets/star-runner.jpg',
    categoria: "sale",
  }];

  export default dataBase;